config/routes.rb
Ticketdesk::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  resources :tickets do
    put 'ticket_response', :on => :member
    get 'close_ticket', :on => :member
    put 'add_issues', :on => :member
  end
  resources :customers
  resources :issues do
    put 'add_note', :on => :member
    put 'create_from_partial', :on => :member
  end
  resources :users
  resources :sessions
  resources :accounts do
    put 'new', :on => :member
  end
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "accounts#new", :as => "sign_up"
  
  
  root :to => "tickets#index"

end

app/models/issue.rb
class Issue 
  include MongoMapper::Document
  
  key :account_id, ObjectId, :required => true
  key :name, String, :required => true
  key :description, String
  key :projected, Date
  key :notes, Array
  timestamps!
  
  attr_accessible :account_id, :description, :name, :new_note
  attr_accessor :new_note
  attr_reader :new_note
  has_many :ticket
  has_many :note
  
  def new_note=(new_note)
  end
  
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  
  def index
      @issue = Issue.find_all_by_account_id(current_user.account_id)
      respond_to do |format|
        format.html
        format.json { render :json => @issue}
      end
  end
  
  def new
    @issue = Issue.new
  end
  
  def create
    #Dep'd, but may re-use
    @issue = Issue.create(params[:issue])
    @issue.account_id = current_user.account_id
    if @issue.save
      redirect_to @issue, notice: 'Issue Added'
    end
  end
  
  def show
    @issue = Issue.find(params[:id])
    @issue_notes = Note.find_all_by_issue_id(@issue.id.to_s).sort_by( &:created_at )
    @ticket = Ticket.find_all_by_issueid_and_status(@issue.id.to_s, 'Open')
    @closed_ticket = Ticket.find_all_by_issueid_and_status(@issue.id.to_s, 'Closed')
  end
  
  def create_from_partial
    issue = Issue.create(:name => params[:name], :description => params[:description], :account_id => current_user.account_id)
    ticket = Ticket.find(params[:id])
    if issue.save
      ticket.issueid.push(issue.id.to_s)
      ticket.save
      redirect_to ticket, notice: 'Issue Created'
    end
  end
  
  def add_note
    issue = Issue.find(params[:id])
    note = Note.create(:account_id => issue.account_id,
                       :issue_id => issue.id,
                       :content => params[:content],
                       :user => current_user.id,
                       :emailed => params[:email])
    
    if note.save
      #Send e-mail updates / close tickets if selected
      issue_update_mail(issue, params[:note]) if params[:email] == "1"
      close_tickets(issue) if params[:close_tickets] == "1"
      redirect_to issue, notice: 'Note Added'
    end
  end
  
  def issue_update_mail(issue, issue_update)
    tickets = Ticket.find_all_by_issueid(issue.id.to_s)
    tickets.each do |t|
      TicketMailer.delay.issue_update(t, issue_update)
    end
  end
  
  def close_tickets(issue)
    tickets = Ticket.find_all_by_issueid(issue.id.to_s)
    tickets.each do |t|
      t.status = "Closed"
      t.save
      TicketMailer.delay.ticket_closed(t)
    end
  end

  
end

app/helpers/issues_helper.rb
module IssuesHelper
  
  def total_tickets_by_issue(issue)
    tickets = Ticket.find_all_by_issueid_and_account_id(issue.id.to_s, current_user.account_id)
    return tickets.size
  end
  
  def total_open_tickets_by_issue(issue)
    tickets = Ticket.find_all_by_issueid_and_account_id_and_status(issue.id.to_s, current_user.account_id, 'Open')
    return tickets.size
  end
  
  def total_closed_tickets_by_issue(issue)
    tickets = Ticket.find_all_by_issueid_and_account_id_and_status(issue.id.to_s, current_user.account_id, 'Closed')
    return tickets.size
  end
  
  def new_note(note)
  end
  
  def note_user_name(user)
    submitter = User.find_by_id(user)
    return submitter.name
  end

  
end

app/views/issues/_new_note.html.erb
<%= form_tag add_note_issue_path, :method => :put, :id => 'new_note' do %>

<%= text_area_tag "content", nil, :class => 'input-xlarge span12' %>  

<%= check_box_tag "email"%> Email note to associated Tickets  <br /> 
<%= check_box_tag "close_tickets" %> Close associated Tickets <br /> <br />

<%= submit_tag "Add Note", :class => 'btn btn-primary' %> 
<% end %>

app/views/issues/_notes_list.html.erb
<table class="table table-condensed note-table">
<% @issue_notes.each do |note| %>
<tr>
	<td <% if note.emailed == true %> class="highlighted_note" <% end %> >
			<%= note.content %> 
			<h6><%= note_user_name(note.user) %>, <%= active_for(note)%> ago </h6>
	</td>
</tr>
<% end %>
</table>

app/views/issues/index.html.erb
<table id="issue-table" class="table table-striped">
  <thead>
    <tr>
      <th>Name <i class="icon-chevron-down"></i></th>
      <th>Total Open Tickets <i class="icon-chevron-down"></i></th>
	  <th>Total Tickets <i class="icon-chevron-down"></i></th>
   	  <th> Active For <i class="icon-chevron-down"></i></th>
	<th> Hidden Active </th>
    </tr>
  </thead>
  <tbody>
	<% @issue.each do |issue| %>
	<tr>
		<td> <%= link_to issue.name, issue %> </td>
		<td> <%= total_open_tickets_by_issue(issue) %></td>
		<td> <%= total_tickets_by_issue(issue) %></td>
		<td> <%= active_for(issue) %> </td>
		<td> <%= issue.created_at %> </td>
	</tr>
	<% end %>
	</tbody>
</table>


<script type = "text/javascript">
$(document).ready(function() {
  $('#issue-table').dataTable( {
    "aoColumns": [ 
      null,
      null,
      null,
      {"iDataSort": 4},
      {"sType" : "date", "bVisible" :false}
    ]
  } );
} );
</script>

app/views/issues/show.html.erb
<div class="page-header">
	<h1><%= @issue.name %></h1>
</div>

<div id = "notes-table", class = "span8">
	<div class = "well">
		<p> <%= @issue.description %> </p>
	</div>
	
<p><h4>Responses: </h4><br />
<%= render :partial => "notes_list" %> </p>

<p>
<b>Add Note:</b><br>
<%= render :partial => "new_note"%>
<br />
</p>
</div>


<div id = "notes-table", class = "span3">
	<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Open with this Issue (<%= total_open_tickets_by_issue(@issue) %>)</th>
		</tr>
	</thead>
		<% @ticket.each do |t| %>
		<tr>			
			<td><%= link_to t.name, t %> </td>		
		</tr>
		<% end %>
		
			<tr>
				<th>Closed with this Issue (<%= total_closed_tickets_by_issue(@issue) %>)</th>
			</tr>
		</thead>
			<% @closed_ticket.each do |c_t| %>
			<tr>			
				<td><%= link_to c_t.name, c_t %> </td>		
			</tr>
			<% end %>
		
	</table>
</div>