config/routes.rb
Ticketdesk::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  resources :tickets do
    put 'ticket_response', :on => :member
    get 'close_ticket', :on => :member
    put 'add_issues', :on => :member
  end
  resources :customers
  resources :issues do
    put 'add_note', :on => :member
    put 'create_from_partial', :on => :member
  end
  resources :users
  resources :sessions
  resources :accounts do
    put 'new', :on => :member
  end
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "accounts#new", :as => "sign_up"
  
  
  root :to => "tickets#index"

end

app/models/ticket.rb
class Ticket 
  include MongoMapper::Document
  
  key :account_id, ObjectId
  key :name, String, :required => true
  key :customer_id, ObjectId
  key :issueid, Array
  key :content, String, :required => true
  key :response, Array
  key :status, String
  timestamps!
  
  belongs_to :customer
  has_many :issue
  
  attr_accessible :account_id, :content, :name, :customer_id, :issue_tokens, :issueid, :closed, :submitted_date
  attr_reader :issue_tokens
  
  before_create :set_status
  
  def set_status
    self.status = "Open";
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  
  def index
    @tickets = Ticket.find_all_by_account_id_and_status(current_user.account_id, 'Open').sort_by( &:response['user'] )
  end
  
  def new
    @ticket = Ticket.new
    @issues = Issue.all
  end
  
  def create
    @ticket = Ticket.new(params[:ticket])
    if @ticket.save
      redirect_to @ticket, notice: 'Ticket Added'
    end
  end
  
  def show
    @ticket = Ticket.find(params[:id])
    @customer = Customer.find_by_id(@ticket.customer_id)
    @issues = Issue.find_all_by_id(@ticket.issueid)
  end  
  
  def ticket_response
    ticket = Ticket.find(params[:id])
    ticket.response.push(:ticket_response => params[:ticket_response], :user => current_user.id)
    if ticket.save
      TicketMailer.delay.ticket_response(ticket, params[:ticket_response])
      redirect_to ticket, notice: 'Response Added'
    end
  end
  
  def close_ticket
    ticket = Ticket.find(params[:id])
    ticket.status = 'Closed'
    if ticket.save
      TicketMailer.delay.ticket_closed(ticket)
      redirect_to ticket, notice: 'Ticket Closed'
    end
  end
  
  def add_issues
    ticket = Ticket.find(params[:id])
    #ticket_issue_tokens is a comma separated string, so convert to an array before pushing as an issue
    issues = params[:ticket_issue_tokens].split(",")
    issues.each do |i|
      ticket.issueid.push(i)
    end
    if ticket.save
      redirect_to ticket, notice: 'Issue Added'
    end
  end
  
end

app/helpers/tickets_helper.rb
module TicketsHelper

def ticket_issues(ticket)
  #Create an array of issues, based on the issues id's
  issue_array = ticket.issueid
  issues = Array.new
  issue_array.each do |i|
    issues.push(Issue.find_by_id(i))
  end
  
  return issues
end


def response_pending(ticket)
  #Find the last issue and see if it was a user or customer
  user_or_customer = "You"
  
  if (ticket.response.size > 0)
  last_user_id = ticket.response.last['user']
  user_or_customer = "Customer" if (Customer.find_by_id(last_user_id))
  end

  return user_or_customer
end

def is_customer(id)
  customer = Customer.find_by_id(id)
  return true if (customer)
end

def customer_or_user_name_by_id(id)  
  user = User.find_by_id(id)
  if user
    return user.name
  end
  
  customer = Customer.find_by_id(id)
  if customer
    return customer.name
  end

end
    
  
end

app/views/tickets/_new_issue_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Create Issue</h3>
</div>
<div class="modal-body">
<%= form_tag create_from_partial_issue_path, :method => :put do %>
<br />
<%= label_tag "Name"  %> 
<%= text_field_tag :name %> <br />
<br />
<%= label_tag "Description" %> 
<%= text_area_tag "description", nil, :class => 'input-xlarge span8' %> <br />

<br />
<div class="modal-footer">
<%= submit_tag "Create Issue", :class=>"btn btn-primary" %> <br />
</div>
<% end %>

app/views/tickets/_open_closed.html.erb
<% if @ticket.status == 'Open' %>
	<%= @ticket.status %> | <%= link_to 'Close Ticket', close_ticket_ticket_path %> 
<% else %>
	<%= @ticket.status %>
<% end %>

app/views/tickets/_ticket_response.html.erb
<%= form_tag ticket_response_ticket_path, :method => :put, :id => 'ticket_response' do %>

 <%= text_area_tag "ticket_response", nil, :class => 'input-xlarge span12' %> <br />

<%= submit_tag "Respond to Ticket", :class => 'btn btn-primary' %> 
<% end %>

app/views/tickets/_ticket_updates.html.erb
<table class="table table-condensed">
	<% @ticket.response.each do |response| %>
	<tr>
		<td <% if is_customer(response['user']) %> class="highlighted_note" <% end %> >
			<%= response['ticket_response'].html_safe %> <br />
			<h6>	<%= customer_or_user_name_by_id(response['user']) %> </h6>
		</td>
	</tr>
	<% end %>
</table>

app/views/tickets/edit.html.erb
<%- model_class = @ticket.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/tickets/index.html.erb
<table id="ticket-table" class="table table-striped">
  <thead>
    <tr>
      <th>Ticket Name <i class="icon-chevron-down"></i></th>
      <th>Client <i class="icon-chevron-down"></i></th>
      <th>Issue  <i class="icon-chevron-down"></i></th>
      <th>Active For <i class="icon-chevron-down"></i></th>
	  <th>Hidden Active</th>
	 <th>Last Response <i class="icon-chevron-down"></i></th>
	<th>Hidden Last</th>
	  <th>From<i class="icon-chevron-down"></i></th>	
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to truncate(ticket.name, :length => 30), ticket_path(ticket) %></td>
        <td> <%= link_to truncate((Customer.find_by_id(ticket.customer_id)).name, :length => 30), customer_path(Customer.find_by_id(ticket.customer_id)) %></td>
        <td> <% ticket_issues(ticket).each do |issue| %>
			 <%= link_to issue.name, issue_path(issue) %> <br /> 
	
	 		<% end %>
		</td>
	
        <td> <%= active_for(ticket) %></td>
 		<td><%= ticket.created_at %> </td>

		<td> <%= active_since_updated(ticket) %> </td>
		<td><%=ticket.updated_at %></td>
		
		<td> <%= response_pending(ticket) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>


<script type = "text/javascript">
$(document).ready(function() {
  $('#ticket-table').dataTable( {
    "aoColumns": [ 
      null,
      null,
      null,
      {"iDataSort": 4},
      {"sType" : "date", "bVisible" :false},
	  {"iDataSort": 6},
	  {"sType" : "date", "bVisible" :false},
	  null
    ]
  } );
} );
</script>

app/views/tickets/show.html.erb
<div class="page-header">
	<h1><%= @ticket.name %></h1>
</div>

<div id = "notes-table", class = "span8">
	<div class = "well">
  <p><%= @ticket.content.html_safe %> </p>
	</div>
 <p> 
<h4>Responses: </h4><br />
<%= render :partial => 'ticket_updates' %> </p>

 <p> 
	<b>Respond to Ticket:</b><br>
	 <%= render :partial => 'ticket_response' %> </p>
</div>


<div id = "notes-table", class = "span3">
	<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Ticket Details 
		</tr>
	</thead>
	<tr>
		<td>
			<dt><strong>Customer Name:</strong></dt>
			<dd><%= link_to @customer.name, customer_path(@customer) %></dd>
		</td>
	</tr>
	<tr>
		<td>
			<dt><strong>Status:</strong></dt>
			<%= render :partial => 'open_closed' %>
		</td>
	</tr>
	<tr>
		<td>
			<dt><strong>Created: </strong></dt>
		  <dd><%= @ticket.created_at %> <br />
			  (<%= active_for(@ticket) %> ago) </dd>
		</td>
	</tr>
	<tr>
		<td>
			<dt><strong>Issues:</strong> <a data-toggle="modal" href="#issue-modal" >(create new)</a></dt>
			  <% @issues.each do |issue| %>
					<dd><%= link_to issue.name, issue_path(issue) %></dd>
			  <% end %>
			<br />
			<dd>	
					<%= form_tag add_issues_ticket_path, :method => :put do %>
					<%= text_field_tag :ticket_issue_tokens, "tokens" %> <br />
					<%= submit_tag "Add Issues" %> 

					<% end %></dd>

					
		</td>
	</tr>			
	</table>
	
	<div class="modal hide" id="issue-modal">
		<%= render :partial => "new_issue_modal" %>
	</div>
	
</div>
<script type="text/javascript">
$('#issue-modal').modal('hide')
</script>