config/routes.rb
Ticketdesk::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  resources :tickets do
    put 'ticket_response', :on => :member
    get 'close_ticket', :on => :member
    put 'add_issues', :on => :member
  end
  resources :customers
  resources :issues do
    put 'add_note', :on => :member
    put 'create_from_partial', :on => :member
  end
  resources :users
  resources :sessions
  resources :accounts do
    put 'new', :on => :member
  end
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "accounts#new", :as => "sign_up"
  
  
  root :to => "tickets#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketdesk</title>
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= javascript_include_tag "application.js" %>
  <%= javascript_include_tag "bootstrap-modal.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Ticket Desk", root_path, :class => 'brand' %> 
				<div class = "pull-right">
					<ul class="nav">
					<li>
					 <% if current_user %>
						<%= link_to "Log Out", log_out_path %> 
					<% end %>
					</li></ul></div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span1"> </div>
		<div class="span2">
			 <% if current_user %>
			<ul class="nav nav-pills nav-stacked">
				<%= nav_link 'Tickets', tickets_path %>
				<%= nav_link 'Issues', issues_path %>  
				<%= nav_link 'Customers', customers_path %>
			</ul>
			<% end %>
		</div>
		<div class="span8">
			<% if flash[:error] -%>
			 <div class="alert alert-error"><%=h flash[:error] %></div>
			<% end -%>
			<% if flash[:notice] -%>
			 <div class="alert alert-success" id="alert"><%=h flash[:notice] %></div>
			<% end -%>
			<%= yield %>
		</div>
		<div class="span1"> </div>
	</div>
</body>
</html>

<script type="text/javascript">
	$(function(){
		$("#alert").fadeOut(3000);
	});
</script>