config/routes.rb
Ticketdesk::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"

  resources :tickets do
    put 'ticket_response', :on => :member
    get 'close_ticket', :on => :member
    put 'add_issues', :on => :member
  end
  resources :customers
  resources :issues do
    put 'add_note', :on => :member
    put 'create_from_partial', :on => :member
  end
  resources :users
  resources :sessions
  resources :accounts do
    put 'new', :on => :member
  end
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "accounts#new", :as => "sign_up"
  
  
  root :to => "tickets#index"

end

app/models/account.rb
class Account
  include MongoMapper::Document

  key :name, String, :requied => true
  key :email, String, :required => true
  key :email_password_salt, String
  key :email_password_salt, String

  
  attr_accessible :name, :email, :email_password, :email_password_confirmation
  
  attr_accessor :email_password
    
  # before_save :encrypt_email_password
  
  def encrypt_password
    if email_password.present?
      self.email_password_salt = BCrypt::Engine.generate_salt
      self.email_password_hash = BCrypt::Engine.hash_secret(email_password, email_password_salt)
    end
  end  

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :require_login
  
  def new
    #No create, as form is also responsible for creating a user
     @account = Account.create(:name => params[:company_name], :email => params[:default_from])
      if @account.save
        #Now create the user / initiate a session
        user = User.create(:email => params[:user_email], :account_id => @account.id, :password => params[:password])
        redirect_to root_path, :notice => "Account created. Please log in to continue."
      end
    end

  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/new.html.erb
<%= form_tag new_account_path, :method => :put do %>
<br />
<%= label_tag "Company Name:" %> 
<%= text_field_tag "company_name" %> <br />

<%= label_tag "Support E-mail:" %>  
<%= text_field_tag "default_from" %> <br />

<%= label_tag "Admin Email:" %>  
<%= text_field_tag "user_email" %> <br />

<%= label_tag "Password:" %> 
<%= password_field_tag "password" %> <br />

<%= label_tag "Password Confirmation:" %>  
<%= password_field_tag "password_confirmation" %> <br />

<br />
<%= submit_tag "Create Account" %> <br />
<% end %>